### ISSUE TITLE
Getting error on credit transaction having value in float

### ISSUE THREAD

**Issue by hari604** [scottlaurent/accounting#14]
The library works fine when the when transaction amount is in integer such as 19, 245 etc.

But when the amount is in float such as 2.45, 9.82 etc, in that case I keep getting below error:
"Amount must be an integer(ish) value"

I have implemented this library and love how it works. The only issue I encountered is with floating point numbers.
Is there any way to resolve this error?

Thank you.

**Comment by scottlaurent** [comment]
Please paste the code example here so I can see it. 

Most likely though, you are trying to store a float, in which case you would need to use the Dollar methods like those shown in /tests/LedgerTest.php  -- In other words, if you are directly using the Accounting->addTransaction vs the Accounting->addDollarTransaction you would need to use a Money object.  Using the Dollar transaction you can see where it casts that float into an INT and then into Money.

The reasoning behind why money is handled this way is better explained by the author here: https://github.com/moneyphp/money

**Comment by hari604** [comment]
@scottlaurent 

Thank you for your helpful reply.
I was able to achieve it using all the dollar functions.

Thank you.
